### ISSUE TITLE
BarTab not compatible with Tab Mix Plus's session restore

### ISSUE THREAD

**Issue by SueDNymme** [philikon/BarTab#22]
If TMP's session restore feature is enabled, BarTab works once (right after you install it and restart the browser) and not again.  If you go into TMP's options and check the box marked "Use Firefox's built-in Session Restore feature", BarTab works.

**Comment by philikon** [comment]
TMP is a big mess, and I'm only going to even consider supporting the TMP features that don't duplicate Firefox's features. Sorry, I'm going to have to reject this.

**Comment by phil-s** [comment]
TMP's session manager is better than the default, but not as good as the "Session Manager" extension (which works with Bar Tab), so use that instead to get the best of both worlds. Session Manager will even import your saved TMP sessions!

To switch, disable TMP's session management and crash-recovery options, then install Session Manager, and restart Firefox.
