### ISSUE TITLE
Favicons do not load on new tabs

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#23]
If you tell a link to open in the background it goes on the Tap. What I am seeing though is that even though the new tab is part of the same domain and has the same favicon as the original tab, the favicon does not load until you load the page once. After that it will load the favicon automatically when it goes on the Tap. Is there a way to make it recognize a domain and hence use the favicon for that domain?

Ex.
Clear Cache so no favicons are saved.
go to
https://addons.mozilla.org/en-US/firefox/addon/67651
Right click PrefsNotTools link and tell it to open in new tab
New tab will not have favicon
Click tab to let it load
Close it
On Bartab page open it again in new tab
It will now have a favicon

I am using 1.3.2 from addons.mozilla.org

**Comment by qwerty017** [comment]
Never mind. This was caused by not saving History.

**Comment by philikon** [comment]
The newest BarTab betas are also much better at retrieving favicons for pages.
