### ISSUE TITLE
Direct2D Acceleration support (3.7a)

### ISSUE THREAD

**Issue by Luckz** [philikon/BarTab#26]
I'm running 3.7a4pre, the current nightly, and after I turned on Direct2d acceleration ( http://www.basschouten.com/blog1.php/2010/03/02/presenting-direct2d-hardware-acceleratio ) this afternoon, all my bartab tabs seem dead. They look like normal tabs in the list (not greyed out), they refuse to reload or open any other urls. I tried updating to 1.4b3 but that did not change anything.

**Comment by Luckz** [comment]
Correction: Old tabs _are_ greyed out for a moment just when starting, but then are immediately 'loaded' and turned into dead tabs.

**Comment by philikon** [comment]
I just tried BarTab on the current mozilla-central tip (3.7a4pre) and a lot of things seem to be broken. This is going to take a fair bit of debugging, so don't expect a bugfix any time soon. There's a reason why BarTab only supports 3.6.x so far... ;)

**Comment by Luckz** [comment]
I used it with 3.7 before without any issues. But yeah, I also have no problem using 3.6 until you get this fixed :).

**Comment by philikon** [comment]
Well, it just so happens somebody knew what was wrong and fixed the major problems in commit de897164f991796294080d9f47b7f683ab103f84...

**Comment by Luckz** [comment]
Basic functionality (actually loading tabs) works now, but the greying out of inactive tabs is still not working.

**Comment by philikon** [comment]
Yep, and it doesn't just happen on Windows with Direct3D or something. Moreover, there are other issues, such as the context menu items not appearing.

However, I'm again going to put this on the back burner for now since there are more important issues to resolve. After all less than 1% of BarTab users use Firefox 3.7a*. I will likely back to it for BarTab 1.5, though.

**Comment by philikon** [comment]
Actually I've looked into this in more detail for other reasons and found that the fixes were quite easy. I've just pushed out 1.4b5 which should now be fully functional on Firefox 3.7a4. Therefore closing this issue. If you still happen to find problems, let me know and we can always reopen this issue or open a new one. Cheers!
