### ISSUE TITLE
1.4's switching to another loaded tab when you close one

### ISSUE THREAD

**Issue by Luckz** [philikon/BarTab#29]
My tab bar looks like this, L for loaded, N for not loaded (on tab); brackets are for the active tab:
N N L N L N N N N N [L] N N
Now from the last L, I middleclick ten links =>
N N L N L N N N N N [L] L L L L L L L L L L N N
Now I close the tab I was using:
N N L N [L] N N N N N L L L L L L L L L L N N
It makes absolutely no sense to me that, if an active tab is one tab to the right, I get thrown six tabs to the left instead.

**Comment by philikon** [comment]
Hmm, good point. Perhaps instead of first walking left and then right, BarTab should pick the closest tab that's loaded, no matter which way it is.

**Comment by Luckz** [comment]
(Maybe a checkbox to just turn this feature off would also help)

**Comment by philikon** [comment]
Also a good point!

**Comment by vijayd** [comment]
I agree with Luckz. Please provide an option to turn this feature off. I had to disable BarTab just because of this. Its a great extension; please fix soon. Thanks.

**Comment by philikon** [comment]
When finding the closest loaded tab, don't first walk left and then right, but actually look both ways at the same time.

This closed by 7b2e717d9c9abef708e11f4877f449e7d2299a71.
