### ISSUE TITLE
Explain "Always Keep Pages from These Sites Loaded" feature in UI

### ISSUE THREAD

**Issue by jny555** [philikon/BarTab#30]
I'm not sure if I'm using this feature incorrectly, but it doesn't seem to be working properly. It would be nice if you provided an example of how things should be formatted. Also, are wild cards (*) acceptable?

**Comment by philikon** [comment]
Sites are meant literally, in other words the list should contain hostnames (e.g. www.google.com). Wild cards do not work.

**Comment by jny555** [comment]
Hmm... I've tried many variations and none of them seem to work.  For instance, if I want Gmail to always open, I've added:
www.gmail.com
http://www.gmail.com
htttps://www.gmail.com
https://mail.google.com/mail/#
http://mail.google.com/mail/#
https://www.mail.google.com/mail/#
https://www.mail.google.com
http://www.mail.google.com

**Comment by philikon** [comment]
http:// etc. are not part of the hostname. For Gmail the hostname is mail.google.com, not www.gmail.com or something. I personally find that the easiest way to get things on and off the whitelist is to use the context menu on a particular tab. That way you don't have to type anything and don't have to guess what the hostname is (though of course I don't think that's too difficult since the hostname is always shown in the location bar, but you've just proven me wrong :)).

**Comment by jny555** [comment]
hahaha... Well the add-on doesn't specify to just use the hostname :) 

BTW, you mentioned that you can add something to the white list through the context menu for a particular tab... I had no idea you could do that. You might want to add a note in the add-on.  That's a big saver.  Thanks for your help!

Edit: I realized that for some reason FF didn't detect that I needed to update the add-on. After uninstalling & re-installing it, I saw exactly what you meant.

**Comment by philikon** [comment]
I thought the screenshots on https://addons.mozilla.org/firefox/addon/67651 as well as the changelog for version 1.4.x would speak for themselves, but apparently I was wrong. I'll consider adding a note to the preference window.

**Comment by jny555** [comment]
Alright, was just a suggestion because once most people download it the first time (which in my case was way before 1.4.x, they rarely will go back to the addon page.  And if they do go back to the page, it's not to check out screenshots or the changelog, just to re-dl it).

Best of luck & thanks for your help.

**Comment by philikon** [comment]
Explain the host whitelist in the UI.

Closed by b8d0de12c3cac35bec93713e7a4049c5058e28f7
