### ISSUE TITLE
Google Reader

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#42]
When pressing "V" to open a feed in a new tab tyhe tab loads automatically rather than sitting unloaded as it would do if I Right-clicked and selected Open in New Tab.

**Comment by philikon** [comment]
Can you try the latest beta, 2.0b1, and see if the problem persists? It _should_ fix it. If not, we'll reopen this issue. Thanks!

**Comment by qwerty017** [comment]
Unfortunately the tabs are still loading immediately wen pressing "V" though I did just find another problem which may have been caused when you added support for Tab Popup. Now when pressing "V" the tab loads immediately (TAB A) and Tab Popup shows the correct URL and title and everything. If I then click on the tab though the URL disappears from the "Location Bar". If I then click on a different tab (TAB B) and hover over TAB A it now shows "about:blank" as the URL.

Also, Bartab does think the immediately loaded tab is no loaded yet. I found out by trying different settings in the config area and by setting it to ask if I want a tab loaded when clicked on, it shows the message even though the page is loaded already after pressing "V". If I can give you any more info to help just ask and you shall receive. :)

**Comment by qwerty017** [comment]
I found another bug which looks like it is tied into this one. If it's not I'll open a new ticket for it.
Go to http://forum.xda-developers.com/showthread.php?p=2718492#post2718492
Left-Click on link under "Solved!".
New tab is automatically loaded.
Is this the same bug or a or should I open a new ticket?

**Comment by philikon** [comment]
Ok, sigh, looks like I'll have to install Google Reader to track this down then. This is likely going to take some time.

As for your other problem: this link doesn't open a tab in the background but in the foreground. BarTab never prevents those from loading.

**Comment by qwerty017** [comment]
Ah. Ok. I wonder if that is why it doesn't block Google Reader tabs as well.

**Comment by qwerty017** [comment]
Looks like the problem is that it opens in a foreground tab. I installed
http://userscripts.org/scripts/show/69161
and when pressing "B" the tab does not load.

Also, before I open a Feature Request, if I request it, would you consider adding in the ability to block tabs that load in foreground?

**Comment by philikon** [comment]
I'm confused now. Can we close this issue then? Or is there an actual problem with BarTab?

Regarding your feature request, I'm not too optimistic about it making into BarTab. It definitely wouldn't be high up on my list.

**Comment by qwerty017** [comment]
Ok. Yeah. Looks like it can be closed since it's not Bartab. Closing issue.
