### ISSUE TITLE
POST is not passed on unloaded tabs

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#45]
If a form tries to post to target="_blank", your plugin converts the POST to a GET
Test Page: http://epii.info/ptest/src.html - click the button
Expected result: page that says POST and the variables passed
What happens with plugin: says GET and indicates nothing was passed.

**Comment by philikon** [comment]
Fixed in commit 1c46bd633c5604bc6d0123cfa96d13ff9fd45606
