### ISSUE TITLE
Javascript tabs load when clicked twice

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#46]
Go to the following website.
http://www.duluthtrading.com/store/products/43145.aspx
Click zoom below the picture.
A new tab will open without loading the picture.
Click zoom again and it will now load the tab with the picture without the tab being clicked on.

**Comment by philikon** [comment]
Closed in commit f22d0671babcf093803656d1acf30544de6a0edb

**Comment by qwerty017** [comment]
Works perfectly. Thanks for the update.
