### ISSUE TITLE
No URI for diverted background tabs

### ISSUE THREAD

**Issue by zumlin** [philikon/BarTab#48]
When BarTab is set not to load background tabs, browser.tabs.loadDivertedInBackground is enabled and a link is opened from an external application, that unloaded tab does not have a URI. If you bookmark it, it bookmarks about:blank and If you close it and undo close tab, a blank tab is opened.

**Comment by philikon** [comment]
Thanks for the report! Somehow caused a race condition with internal browser components. Crude but effective fix in commit 798408f29628b1c57b6630d8bec8347dfe9f28ee.

**Comment by zumlin** [comment]
Thanks for the fix.
