### ISSUE TITLE
wyciwyg links (e.g. from GMail) do not load

### ISSUE THREAD

**Issue by qwerty017** [philikon/BarTab#50]
When clicking a link that is spelled out in GMail such as www.chase.com in GMail the tab is created but when clicking on it nothing is loaded. If I hover over the tab Tab Popup reports the correct URL of www.chase.com or whatever. If I continue hovering until that Yellow Banner comes up at which point the URL is shown to be a URL starting with "wyciwyg://" . When I then click on the tab a blank page is shown and the Address Bar just shows "Type a Web Address". If you have GMail I can forward the emails in question to you if you cannot see the problem yourself.

**Comment by qwerty017** [comment]
Oh yeah. This only happens when links are spelled out. Not when the link says "Chase" and is an href to www.chase.com. In those cases BarTab loads them fine.

**Comment by philikon** [comment]
Commit d67e3580820ed89a65cbbdbffcadb1e4f7afa909 fixes the handling of wyciwyg:// URIs. Not necessarily in a completely satisfactory way, but it'll have to do for now.

**Comment by qwerty017** [comment]
Works perfectly. Thanks for the update.
