### ISSUE TITLE
"Sort Tabs" add-on hidden in Beta 2.04b

### ISSUE THREAD

**Issue by TooTiredToSleep** [philikon/BarTab#51]
https://addons.mozilla.org/en-US/firefox/addon/5372/

Tested with both the latest stable release and the latest beta and in the beta, the right click option to sort the tabs is missing. Disabling bartab or going back to stable release makes it appear again.

**Comment by TooTiredToSleep** [comment]
Testing the latest Sort Tab update appears to have fixed this problem.

 Version 2.100530.15  — May 29, 2010  — 56 KB

Fixed: Compatibility with BarTab. Tab context menu entries were not displayed. Thank to Maxime tester of 2.14 for reporting.

**Comment by philikon** [comment]
Thanks for the update. Closing this.
