### ISSUE TITLE
NewTabURL - triggers sometimes when restoring unloaded tabs.

### ISSUE THREAD

**Issue by Drugoy** [philikon/BarTab#52]
NewTabURL sometimes "hooks" the unloaded tab (when you activate it) first and opens the address (configured by the NewTabURL), but if the tab had a history and it was unloaded - it should do nothing more, than strictly get loaded when you activate it.
It happens not all the time, but sometimes, especially when you load many unloaded tabs at once.
Steps to reproduce: 1. Open 11 tabs.
2. Let 10 of them get unloaded (by BarTab).
3. Activate them all one after another in a short time.
Normally all of them should be just restored, but sometimes NewTabURL hooks and it opens pre configured URL instead.

**Comment by philikon** [comment]
Which version of BarTab are you using?

**Comment by Drugoy** [comment]
happens with both: 1.5.1 and 2.0b4, but as I replied you in email - this bug happens less with 2.0b4 + if not scrolling many unloaded tabs at once - bug usually doesn't even happen.

**Comment by Drugoy** [comment]
could you please try to fix that incompatibility, please? :(
