### ISSUE TITLE
Apparent Compatibility with TabMixPlus

### ISSUE THREAD

**Issue by maringuy** [philikon/BarTab#54]
I’m currently running Firefox 3.5 and as was stated on the Firefox BarTab page in their extensions section, version 2.0 of BarTab isn’t fully compatible with that version of Firefox.  in addition, for some reason, I’m unable to manually load or unload tabs.  FYI, the reason I haven’t upgraded to FF 3.6 is that version (at least in my case) is not compatible with TabMixPlus, which is a “deal breaker” for me as I love what it does.  

So I’m wondering if a previous version of BarTab would work with FF 3.5 and if so, where could I find it?

Thanks.

**Comment by philikon** [comment]
Tab Mix Plus works just fine on Firefox 3.6 (as fine as Tab Mix Plus can ever work, that is). I can highly recommend upgrading to Firefox 3.6 anyway. I can also highly recommend ditching Tab Mix Plus. :)

You can get previous versions of BarTab from https://addons.mozilla.org/en-US/firefox/addons/versions/67651 (this page is linked as "View All Versions" from the main add-on page). The last stable version before 2.0 was 1.5.1.
