### ISSUE TITLE
Feature Context Menu to Reload All Loaded Tabs

### ISSUE THREAD

**Issue by aGitHubUser** [philikon/BarTab#58]
The Should be an option to reload only the tabs that haven't been unloaded.

**Comment by aGitHubUser** [comment]
The Reload All Tabs options does what it says and reloads all the pages, when I would like to able to reload only the pages, I have haven't chosen to unload.

Currently I have to either click on each tab individually and hit F5, or unload all tabs and then reselect the ones I want. Both of which are inconvenient when you have enough tabs open to warrant using BarTab in the first place.

**Comment by aGitHubUser** [comment]
Re-posted as issue 67, due to closing my own report.

**Comment by philikon** [comment]
Kind of a dupe of #10.
