### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by leomeloxp** [philikon/BarTab#64]
Is it possible to implement/add some keyboard shortcuts, at least for load and unload tab, that would be more than enough.

One piece of advice is that you can add it to the page context menu, so it would be possible to hit with the context menu key.

**Comment by philikon** [comment]
Well, the context menu key is rather platform specific (Windows) and I wonder how many people actually use it. I'm open to having a keyboard shortcut for Unload Tab. Any suggestion as to what it could be?

**Comment by leomeloxp** [comment]
Well, for the context menu, I don't really use it. But I prefer context menu by keyboard then clicking with the mouse every time. For the keyboard, I think that it could be some kind of Ctrl + <something> or even a customizable one, I don't know how hard it is to do such a thing. 

These are my ideas, I'm not that good with programming so I can't say I would help you guys on actually doing it. But if there's anything I can do, let me know =]
