### ISSUE TITLE
Unloaded tab displays URL?

### ISSUE THREAD

**Issue by reidr** [philikon/BarTab#66]
I just started using BarTab, which seems like a great idea.  On a Windows XP machine I was on earlier (not sure the FF version, maybe a 3.7 beta), it seemed to work fine; on a Linux machine now (FF 3.6.6), unloaded tabs are displaying the URL of the page rather than the title.  When I click on the tab to reload it, the title comes back.  My extensions are fairly similar on both machines, including TMP.  Any idea what might be wrong?  Thanks!

**Comment by philikon** [comment]
BarTab gets the title + icon information from the history database. There may be various reasons why those pages aren't in there (perhaps you turned recording history off?) and it's hard to tell why exactly with the information you've provided. If it's a new profile you're running, it may very well be that the history entries haven't been created yet for some reason. Try it for a few more days and let me know if the problem persists.

**Comment by reidr** [comment]
I haven't explicitly turned history off, as far as I know.  It seems to be on from looking at my prefs.  It's an old profile, and the problem persists after a browser restart.  I guess I will export my list of extensions on my Windows box and compare with those on the Linux box.  Maybe one of them is causing trouble.  Thanks for the help.

**Comment by reidr** [comment]
For the record, the TabRenamizer extension was causing the problem.
