### ISSUE TITLE
Context Menu to Reload All Loaded Tabs

### ISSUE THREAD

**Issue by aGitHubUser** [philikon/BarTab#67]
There Should be an option to reload all the tabs that haven't been unloaded.

The Reload All Tabs options does what it says and reloads all the pages, when I would like to able to reload only the pages, I haven't chosen to unload.

Currently I have to either click on each tab individually and hit F5, or unload all tabs and then reselect the ones I want. Both of which are inconvenient when you have enough tabs open to warrant using BarTab in the first place.

And yes I have posted this before (issue 58), but I managed to close my own report, so I imagine it got overlooked.

**Comment by philikon** [comment]
There's no need to create new issues, you can simply reopen old ones. Anyway, this is a dupe of #58 which in itself is kind of a dupe of #10.
