### ISSUE TITLE
BarTab shows duplicate tabs in Firefox 4 beta 5

### ISSUE THREAD

**Issue by b10c77** [philikon/BarTab#76]
BarTab shows duplicate tabs when used with FireFox beta 5. This happens after unloading a tab and re-loading it. I can send a screenshot if needed.

**Comment by b10c77** [comment]
Here's a screenshot of what happens:
http://img153.imageshack.us/img153/7996/bartabissue.png

**Comment by philikon** [comment]
Fixed in changeset c50a5dfaf62048178082f7c73a04ab73f853a080
