### ISSUE TITLE
Duplicate tabs created in firefox 4.0b6

### ISSUE THREAD

**Issue by Super-Pickle** [philikon/BarTab#82]
I found an issue where my tabs will duplicate themselves if bar tab is set to unload a page after a set amount of time.

I'll end up with one loaded tab, and one unloaded tab after bar tab tries to unload a tab. It does unload the tab, but it never closes the old tab.

I've listed my add-ons besides bar tab, because it's most likely a comparability problem. 
I'm also running Vista.

Default extensions (Feedback/Microsoft framework)
Add-on compatibility reporter
Tab utilities
Personas expression
xmarks
Noscript

I've disabled the feature until it can be fixed.

**Comment by philikon** [comment]
Dupe of #76 and already fixed in 2.1b1
