### ISSUE TITLE
Tabs that unload after a period of time duplicate and cannot be closed in FF 4.0b6

### ISSUE THREAD

**Issue by claytron** [philikon/BarTab#86]
I have tabs unload after 45 minutes of inactivity. In the latest Firefox 4 beta, these tabs will unload, but leave behind a duplicate tab that cannot be accessed. The unloaded tab can no longer be closed either.

Here is my version info, Latest beta and Pentadactyl nightly. I haven't tested to see if another add-on might be causing the issue.

```
Pentadactyl hg4737 (created: 2010/10/24 00:00:12) running on:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0b6) Gecko/20100101 Firefox/4.0b6
```

Here is an image of what it looks like when it happens. I should only have three tabs open here:

<img src="http://imgur.com/aLyNU.png" alt="" title="Hosted by imgur.com" />

**Comment by philikon** [comment]
Already fixed in 2.1b1, mate.
