### ISSUE TITLE
Setting to NOT unload any tabs with forms (to prevent losing partial entries) 

### ISSUE THREAD

**Issue by ghost** [philikon/BarTab#88]
On a nearly daily basis, I will be in the process of filling out a form or entering a discussion board post, but need to fetch a piece of info before proceeding. I hop over, hop back, and my stuff is gone - got zapped by BarTab! Again!

Adding sites to the "do not unload" list is not an answer, since I don't always write in the same places and because many pages I load are from the same sites. If I'm not posting anything, chances are I DO want it to unload it when inactive.

If there is a way to check the page content before unloading, it should be based on the visible content only (i.e. if the form is in a hidden section that hasn't been exposed yet, it should not count).

This problem is enough of a dealbreaker to make me consider stopping using this add-on.  I have lost SO much stuff because of this, it's incredibly annoying. I'm sure I'm not the only one who's experienced it.

**Comment by hackel** [comment]
I would just disable the auto-unload function...

This sounds more like a bug, and as a solution, I believe Firefox's session manager already saves entered form data so it's back when you restart, and Bartab should as well, if possible.

**Comment by ghost** [comment]
The auto-unload function is the key feature of BarTab, so turning that off would render the add-on completely useless (to me anyway).

From my experience FF's session manager does not do a great job of preserving or restoring form data entries either; it seems to depend on the type of form. For that reason I don't think the answer for BarTab lies in trying to capture the form data, but rather just preventing unload if there is a multi-line element active on the page.

**Comment by ghost** [comment]
The auto-unload function is the key feature of BarTab, so turning that off would render the add-on completely useless (to me anyway).

From my experience FF's session manager does not do a great job of preserving or restoring form data entries either; it seems to depend on the type of form. For that reason I don't think the answer for BarTab lies in trying to capture the form data, but rather just preventing unload if there is a multi-line element active on the page.
