### ISSUE TITLE
compatability with 'autoClose tabs' plugin

### ISSUE THREAD

**Issue by amiti** [philikon/BarTab#90]
Is it possible to allow both plugins to work together or alternatively add a feature in BarTab to  automatically close idle tabs after predetermined time length?

**Comment by hackel** [comment]
This is already implemented, enable the "When I don't visit a tab for a while" option in preferences.
See also: extensions.bartab.timeoutValue

**Comment by amiti** [comment]
All I can see is "When I don't visit a tab for a while" -> "unload it after..." option.

What I meant was : after unloading the bar from memory set a timer to remove tab altogether from the tab list.
