### ISSUE TITLE
Unloaded Tabs too faded

### ISSUE THREAD

**Issue by mbrown3** [philikon/BarTab#95]
I love this extension, and find it very useful. However, I had to disable it for now, because I found that the unloaded tabs were just TOO dark/faded. That is, I like the fact that unloaded tabs are kind of faded in the background until they are clicked on/loaded (which makes it very helpful to know which tabs are loaded or not); however, I found that trying to find an unloaded tab is much harder that it should be because they are SO dark. 

I wish there was a way to adjust this option (like, "tab transparency" or something) so that I could lighten them up quite a bit. I would prefer them to just be slightly more faded than a loaded tab...other users will likely prefer them as they are now, or somewhere in-between. But I sometimes frequently switch between various tabs depending on what I'm doing, so I need better visibility of them in order to find the ones I want. 

That said, I do have some tabs that may not be selected/loaded for days at a time, so the basic functionality of BarTab is great for me. Any chance of seeing an adjustable level of transparency/"fade" for the unloaded tabs? 

Thanks!

**Comment by philikon** [comment]
Please see FAQ no. 1: https://github.com/philikon/BarTab/wiki/faq

By default BarTab uses an opacity value of 0.5 for unloaded tabs. 1.0 would be what regular tabs look like, so try to experiment with values in between to see which one you like best. This won't be a configurable option for BarTab.
