### ISSUE TITLE
Tab is duplicated on unload

### ISSUE THREAD

**Issue by ghost** [philikon/BarTab#97]
In Fx 4b9:
When I select a tab, its contents are loaded. If I then right-click on that tab and choose "Unload",  the tab is duplicated: one tab with the content loaded, one unloaded. It is then not possible to select both tabs. Click events on one of the tabs are ignored.

**Comment by philikon** [comment]
Already fixed in 2.1 beta!

**Comment by ghost** [comment]
Cool. :)
Is there a planned release date?

**Comment by philikon** [comment]
Not yet. Need to ship Firefox 4 first!

**Comment by ghost** [comment]
Ok, thanks for the info.
I found the beta stuff and installed it now. :)
